name: backup # show run으로 시스코 config 백업

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: [ self-hosted, linux ] # 별도의 서버의 리눅스 환경에서만 동작하게끔 설정

    steps:
      - name: Checkout repository # 해당 스텝이 없다면 러너에게 job을 전달 할 수 없음.
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install netmiko and paramiko
        # 러너(리눅스 서버)에게 run 동작으로 netmiko를 설치하게한다.
        # 보통 pip install은 이미 설치되었다면 패키지를 덮어쓰거나 스킵하지만 그럼에도 매번 설치하는 의존성을 줄이려면?
        run: |
          python -c "import netmiko" 2>/dev/null || pip install netmiko
          python -c "import paramiko" 2>/dev/null || pip install paramiko


      - name: Run backup script
        run: python backup_config.py # 스크립트 이름 정확히 기재해야함.

      - name: Upload config backup file as artifact # 아티팩트 액션을 이용해 config를 깃허브에 백업한다.
        uses: actions/upload-artifact@v4
        with:
          name: switch-backup
          path: backups/